import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lee D.G",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <body className={inter.className}>
        <Nav />
        <div
          className="page w-full mt-[60px] p-6
          md:p-14
          lg:w-4/5 lg:ml-auto lg:p-10 lg:mt-0
          xl:p-20"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
